version: '2'
services:
  dev:
    image: node:9.6.1
    command: bash
    working_dir: /app
    user: "1000:1000"
    volumes:
    - .:/app
  server:
    image: node:9.5
    working_dir: /app
    command: node_modules/.bin/nodemon express.js
    volumes:
      - .:/app
    ports:
      - "8000:80"
  mongo:
     image: mongo:3.6
     volumes:
       - ./.data:/data/db
